# Generated by Django 3.1.12 on 2025-08-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
