# Generated by Django 3.1.12 on 2025-08-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeApp', '0003_auto_20250826_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('draft', 'Draft')], default='pending', max_length=20),
        ),
    ]
